# basic options
title: Ho Namkung
author: Ho Namkung
email: namkungho87@gmail.com  
description: Biomedical Engineer
googlescholar_username: Ho Namkung
twitter_username: Ho_Namkung
github_username:  honamkung

# Build settings
markdown: kramdown
theme: minima
